### ISSUE TITLE
Login failure with correct credentials

### ISSUE THREAD

**Issue by sterlingbaldwin** [ESGF/output_viewer#6] opened 2017-02-10 21:33 UTC
I can run the same script twice and get different results. Most of the time it succeeds, but from time to time the login credentials are rejected for no apparent reason. Below is the information from the exception. For some reason [this return code](https://github.com/ESGF/output_viewer/blob/master/output_viewer/diagsviewer.py#L23) isnt 200.

```
File "/export_2/baldwin32/projects/acme_workflow/run_scripts/upload_diag_job_8ce4f03dc0a3493f86418625c3225d33.py", line 16, in <module>
    client_id, key = client.login(CORRECT_USER, CORRECT_PASS)
  File "/export_2/baldwin32/anaconda2/envs/acme2/lib/python2.7/site-packages/output_viewer/diagsviewer.py", line 24, in login
    raise ValueError("Username/Password invalid.")
Upload_Diagnostic error connecting to server
1 Inappropriate argument value (of correct type).
2 (<type 'exceptions.ValueError'>, ValueError('Username/Password invalid.',), <traceback object at 0x7fd043e98518>)
3 <type 'exceptions.ValueError'>
4 Username/Password invalid.
5 16
6 None```

**Comment by sterlingbaldwin** [comment] 2017-02-10 21:37
Here's the script that's having this problem. The weird part of this error is it just happens sometimes, and other times the exact same script succeeds.

```
from output_viewer.diagsviewer import DiagnosticsViewerClient
import sys
import traceback
def print_debug(e):
    print '1', e.__doc__
    print '2', sys.exc_info()
    print '3', sys.exc_info()[0]
    print '4', sys.exc_info()[1]
    print '5', traceback.tb_lineno(sys.exc_info()[2])
    ex_type, ex, tb = sys.exc_info()
    print '6', traceback.print_tb(tb)
client = DiagnosticsViewerClient(
    server='http://pcmdi10.llnl.gov:8008',
    cert=False)
try: 
    client_id, key = client.login('CORRECT_USER','CORRECT_PASS')
except Exception as e:
    print 'Upload_Diagnostic error connecting to server'
    print_debug(e)
    sys.exit(1)
try:
    dataset_id = client.upload_package('/p/cscratch/acme/baldwin32/output/coupled_diags/year_set_1')
except Exception as e:
    print 'Error uploading diagnostic set to server'
    print_debug(e)
    sys.exit(1)
```

**Comment by chaosphere2112** [comment] 2017-02-13 16:00
@sterlingbaldwin At a guess, it's probably a server resources issue (since it's nondeterministic). Right now I don't try to give useful error messages at all; any non-200 response will trigger "invalid username/password". I'll dig into it some today.

**Comment by chaosphere2112** [comment] 2017-02-13 17:29
Gonna close this for now; I've added some additional logging in case it happens again, as I was unable to reproduce.

**Closed as completed** 2017-02-13 17:28 UTC
